project:
  type: website
  output-dir: docs

website:
  title: "Cards to Code"
  page-footer: "\xA9 2024 Overbet.ai. All rights reserved."
  open-graph: true
  google-analytics: G-68E8GHZRHQ
  favicon: ./assets/logo.png
  navbar: 
    logo: ./assets/logo.png
    background: dark
    right: 
      - text: "About"
        href: about.qmd
      - text: "Overbet.ai"
        href: https://overbet.ai
    tools: 
      - icon: discord
        href: https://discord.gg/KZQK2xN8Da
      - icon: mailbox2-flag
        href: https://overbetai.substack.com/
      - icon: github
        href: https://github.com/overbetai/cardstocode
  sidebar: 
    style: "docked"
    background: light
    contents:
        - text: "Home (Intro)"
          href: "index.qmd"
        - text: "#1: Game Theory"
          href: "1_gametheory.qmd"
        - text: "#2: Kuhn Poker"
          href: "2_kuhnpoker.qmd"
        - text: "#3: Game Trees"
          href: "3_gametrees.qmd"
        - text: "#4: Regret"
          href: "4_regret.qmd"
        - text: "#5: CFR"
          href: "5_cfr.qmd"
        - text: "#6: Monte Carlo CFR"
          href: "6_mccfr.qmd"
        - text: "#7: Evals and Results"
          href: "7_kuhncfr.qmd"
        - text: "#8: 100-card Kuhn"
          href: "8_100cardkuhn.qmd"
        - text: "#9: Opponent Modeling"
          href: "9_opponentmodeling.qmd"
        - text: "#10: Challenge Projects"
          href: "10_challenge.qmd"
        - text: "Next Directions"
          href: "next.qmd"
format:
  html:
    theme: 
      - cerulean
    grid:
      sidebar-width: 240px
    math: true 
    html-math-method: katex
    toc: true
    toc-expand: true